// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/simple-choice/MultipleChoice.tsx": () => import("../components/mockups/simple-choice/MultipleChoice.tsx"),
  "./components/mockups/simple-choice/SelectionLimit.tsx": () => import("../components/mockups/simple-choice/SelectionLimit.tsx"),
  "./components/mockups/simple-choice/SingleChoice.tsx": () => import("../components/mockups/simple-choice/SingleChoice.tsx")
};
